# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pajeng_dump <- function() {
    .Call(`_pajengr_pajeng_dump`)
}

rcpp_hello_world <- function() {
    .Call(`_pajengr_rcpp_hello_world`)
}

